export const offersMockup = [
	{
		city: 'Warszawa',
		province: 'Mazowieckie',
		title: 'Super atrakcja w Warszawie',
		price: 110,
		priceCurrency: 'zł',
		category: 'Jazda konno',
		src: 'https://placehold.jp/300x200.png',
	},
	{
		city: 'Gdańsk',
		province: 'Pomorskie',
		title: 'Niesamowita atrakcja w Gdańsku',
		category: 'Trampoliny',
		price: 140,
		priceCurrency: 'zł',
		src: 'https://placehold.jp/300x200.png',
	},
	{
		city: 'Kraków',
		province: 'Pomorskie',
		title: 'Niesamowita atrakcja w Krakowie',
		category: 'Zwiedzanie',
		price: 240,
		priceCurrency: 'zł',
		src: 'https://placehold.jp/300x200.png',
	},
	{
		city: 'Wrocław',
		province: 'Dolnośląskie',
		title: 'Super atrakcje Wrocław',
		category: 'Muzeum',
		price: 40,
		priceCurrency: 'zł',
		src: 'https://placehold.jp/300x200.png',
	},
	{
		city: 'Wrocław',
		province: 'Dolnośląskie',
		title: 'Super atrakcje Wrocław',
		category: 'Muzeum',
		price: 40,
		priceCurrency: 'zł',
		src: 'https://placehold.jp/300x200.png',
	},
	{
		city: 'Wrocław',
		province: 'Dolnośląskie',
		title: 'Super atrakcje Wrocław',
		category: 'Muzeum',
		price: 40,
		priceCurrency: 'zł',
		src: 'https://placehold.jp/300x200.png',
	},
	{
		city: 'Wrocław',
		province: 'Dolnośląskie',
		title: 'Super atrakcje Wrocław',
		category: 'Muzeum',
		price: 40,
		priceCurrency: 'zł',
		src: 'https://placehold.jp/300x200.png',
	},
	{
		city: 'Wrocław',
		province: 'Dolnośląskie',
		title: 'Super atrakcje Wrocław',
		category: 'Muzeum',
		price: 40,
		priceCurrency: 'zł',
		src: 'https://placehold.jp/300x200.png',
	},
];

